# -*- coding: utf-8 -*-
"""
Created on Thu Apr 02 14:37:18 2020

@author: davem
"""
plt.rcParams['font.sans-serif'] = "Arial"
plt.rcParams['font.family'] = "sans-serif"

#%% Code to plot variance in results based on initial conditions for Rapa
testFig = plt.figure()
test = plt.subplot(111)
test.plot(ts, CD4s_Rapa_Data_m_lowTregs[1,:], 'g--', label = '1% Tregs')
test.plot(ts, CD4s_Rapa_Data_m_2pctTregs[1,:], 'g', label = '2% Tregs')
test.plot(ts, CD4s_Rapa_Data_m_3pctTregs[1,:], 'g:', label = '3% Tregs')
test.fill_between(ts, CD4s_Rapa_Data_m_lowTregs[1,:],CD4s_Rapa_Data_m_3pctTregs[1,:],color = 'green', alpha = 0.2)
test.plot(ts, CD4s_Rapa_Data_m_lowTregs[2,:], 'r--', label = '1% Tregs')
test.plot(ts, CD4s_Rapa_Data_m_2pctTregs[2,:], 'r', label = '2% Tregs')
test.plot(ts, CD4s_Rapa_Data_m_3pctTregs[2,:], 'r:', label = '3% Tregs')
test.fill_between(ts, CD4s_Rapa_Data_m_lowTregs[2,:],CD4s_Rapa_Data_m_3pctTregs[2,:],color = 'red', alpha = 0.2)
test.legend(loc = 'best', fontsize = 16)
test.set_xlabel('Time (Hours)', size = 20)
test.set_ylabel('Fraction of CD4 T cells', size = 20)
test.set_xticks(ticks = [0,50,100,150])
test.set_xticklabels(labels = [0,50,100,150], fontsize = 16)
test.set_yticks(ticks = [0,0.2,0.4,0.6,0.8,1.0])
test.set_yticklabels(labels = [0,0.2,0.4,0.6,0.8,1.0], fontsize = 16)
test.set_ylim(0,1.0)
test.set_xlim(0,150)

#%% Code to plot variance in results based on initial conditions for TGF
testFig = plt.figure()
test = plt.subplot(111)
test.plot(ts, CD4s_TGF_Data_m_lowTregs[1,:], 'g--', label = '1% Tregs')
test.plot(ts, CD4s_TGF_Data_m_2pctTregs[1,:], 'g', label = '2% Tregs')
test.plot(ts, CD4s_TGF_Data_m_3pctTregs[1,:], 'g:', label = '3% Tregs')
test.fill_between(ts, CD4s_TGF_Data_m_lowTregs[1,:],CD4s_TGF_Data_m_3pctTregs[1,:],color = 'green', alpha = 0.2)
test.plot(ts, CD4s_TGF_Data_m_lowTregs[2,:], 'r--', label = '1% Tregs')
test.plot(ts, CD4s_TGF_Data_m_2pctTregs[2,:], 'r', label = '2% Tregs')
test.plot(ts, CD4s_TGF_Data_m_3pctTregs[2,:], 'r:', label = '3% Tregs')
test.fill_between(ts, CD4s_TGF_Data_m_lowTregs[2,:],CD4s_TGF_Data_m_3pctTregs[2,:],color = 'red', alpha = 0.2)
test.set_xlabel('Time (Hours)', size = 20)
test.set_ylabel('Fraction of CD4 T cells', size = 20)
test.set_xticks(ticks = [0,50,100,150])
test.set_xticklabels(labels = [0,50,100,150], fontsize = 16)
test.set_yticks(ticks = [0,0.2,0.4,0.6,0.8,1.0])
test.set_yticklabels(labels = [0,0.2,0.4,0.6,0.8,1.0], fontsize = 16)
test.set_ylim(0,1.0)
test.set_xlim(0,150)

#%% Code to plot variance in results based on initial conditions
testFig = plt.figure()
test = plt.subplot(111)
test.plot(ts, CD4s_Combo_Data_m_lowTregs[1,:], 'g--', label = '1% Tregs')
test.plot(ts, CD4s_Combo_Data_m_2pctTregs[1,:], 'g', label = '2% Tregs')
test.plot(ts, CD4s_Combo_Data_m_3pctTregs[1,:], 'g:', label = '3% Tregs')
test.fill_between(ts, CD4s_Combo_Data_m_lowTregs[1,:],CD4s_Combo_Data_m_3pctTregs[1,:],color = 'green', alpha = 0.2)
test.plot(ts, CD4s_Combo_Data_m_lowTregs[2,:], 'r--', label = '1% Tregs')
test.plot(ts, CD4s_Combo_Data_m_2pctTregs[2,:], 'r', label = '2% Tregs')
test.plot(ts, CD4s_Combo_Data_m_3pctTregs[2,:], 'r:', label = '3% Tregs')
test.fill_between(ts, CD4s_Combo_Data_m_lowTregs[2,:],CD4s_Combo_Data_m_3pctTregs[2,:],color = 'red', alpha = 0.2)
test.set_xlabel('Time (Hours)', size = 20)
test.set_ylabel('Fraction of CD4 T cells', size = 20)
test.set_xticks(ticks = [0,50,100,150])
test.set_xticklabels(labels = [0,50,100,150], fontsize = 16)
test.set_yticks(ticks = [0,0.2,0.4,0.6,0.8,1.0])
test.set_yticklabels(labels = [0,0.2,0.4,0.6,0.8,1.0], fontsize = 16)
test.set_ylim(0,1.0)
test.set_xlim(0,150)

#%% Code to plot variance in results based on initial conditions
testFig = plt.figure()
test = plt.subplot(111)
test.plot(ts, CD4s_Control_Data_m_lowTregs[1,:], 'g--', label = '1% Tregs')
test.plot(ts, CD4s_Control_Data_m_2pctTregs[1,:], 'g', label = '2% Tregs')
test.plot(ts, CD4s_Control_Data_m_3pctTregs[1,:], 'g:', label = '3% Tregs')
test.fill_between(ts, CD4s_Control_Data_m_lowTregs[1,:],CD4s_Control_Data_m_3pctTregs[1,:],color = 'green', alpha = 0.2)
test.plot(ts, CD4s_Control_Data_m_lowTregs[2,:], 'r--', label = '1% Tregs')
test.plot(ts, CD4s_Control_Data_m_2pctTregs[2,:], 'r', label = '2% Tregs')
test.plot(ts, CD4s_Control_Data_m_3pctTregs[2,:], 'r:', label = '3% Tregs')
test.fill_between(ts, CD4s_Control_Data_m_lowTregs[2,:],CD4s_Control_Data_m_3pctTregs[2,:],color = 'red', alpha = 0.2)
test.set_xlabel('Time (Hours)', size = 20)
test.set_ylabel('Fraction of CD4 T cells', size = 20)
test.set_xticks(ticks = [0,50,100,150])
test.set_xticklabels(labels = [0,50,100,150], fontsize = 16)
test.set_yticks(ticks = [0,0.2,0.4,0.6,0.8,1.0])
test.set_yticklabels(labels = [0,0.2,0.4,0.6,0.8,1.0], fontsize = 16)
test.set_ylim(0,1.0)
test.set_xlim(0,150)
